version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: reserveapp
      POSTGRES_PASSWORD: my3TrON6ao8sdu
      POSTGRES_DB: main
    ports:
      - "5410:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: